---
- hosts: all
  become: true

  handlers:
    - name: restart apache
      service:
        name: httpd
        state: restarted

  tasks:
    - name: Ensure Apache is installed
      package:
        name: httpd
        state: present

    - name: Copy a web page
      copy:
        content: |
          <html>
          <head><title>Hello!</title></head>
          <body>What did you expect?</body>
          </html>
        dest: "/var/www/html/index.html"
        mode: 0664
      notify: restart apache

    - name: Ensure apache is running and starts on boot
      service:
        name: httpd
        state: started
        enabled: true
